name: "Release package"
on: [push]


env:
  release: minor
                
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                adapter: [ 'core' ]
                node-version: [ 14.x ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup Node
                uses: actions/setup-node@v2
                with:
                    node-version: '14.x'
                    registry-url: 'https://registry.npmjs.org'
            -   name: Run my action
                run: |
                    echo "::set-output NEW_VERSION=::$(npm --no-git-tag-version version major)" >> $GITHUB_ENV 
                shell: bash
                
            -   name: Next Step
                run: echo ${{ env.NEW_VERSION }} 

