name: "Release package"
on:
    workflow_dispatch:
        inputs:
            releaseType:
                description: 'Release type (one of): patch, minor, major, prepatch, preminor, premajor, prerelease'
                options:
                    - patch
                    - minor
                    - major
                required: true
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                adapter: [ 'core' ]
                node-version: [ 14.x ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup Node
                uses: actions/setup-node@v2
                with:
                    node-version: '14.x'
                    registry-url: 'https://registry.npmjs.org'
            
            # Bump package version
            # Use tag latest
            -   name: Bump release version
                if: startsWith(github.event.inputs.releaseType, 'pre') != true
                run: |
                    echo "NEW_VERSION=$(npm --no-git-tag-version version ${{ env.RELEASE_TYPE }}" >> $GITHUB_ENV
                    echo ${{ env.NEW_VERSION }}
                env:
                    RELEASE_TYPE: ${{ github.event.inputs.releaseType }}
            
            # Bump package pre-release version
            # Use tag beta for pre-release versions
            -   name: Bump pre-release version
                if: startsWith(github.event.inputs.releaseType, 'pre')
                run: |
                    echo ${{ env.RELEASE_TYPE }}
                    echo "NEW_VERSION=$(npm --no-git-tag-version --preid=beta version env.RELEASE_TYPE)" >> $GITHUB_ENV
                env:
                    RELEASE_TYPE: ${{ github.event.inputs.releaseType }}
            
            # Update changelog unreleased section with new version
            -   name: Update changelog
                uses: superfaceai/release-changelog-action@v1
                with:
                    path-to-changelog: CHANGELOG.md
                    version: ${{ env.NEW_VERSION }}
                    operation: release
            
            # Commit changes
            -   name: Commit CHANGELOG.md and package.json changes and create tag
                run: |
                    git add .
                    git commit -m "chore: release ${{ env.NEW_VERSION }}"
                    git tag ${{ env.NEW_VERSION }}
            
            -   name: Install dependencies and build 🔧
                run: |
                    cd packages/${{ matrix.adapter }}
                    && npm install
                    && npm version ${{ env.NEW_VERSION }}
                    && npm publish
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            
            # Push repository changes
            -   name: Push changes to repository
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    git push origin && git push --tags
            
            # Update GitHub release with changelog
            -   name: Update GitHub release documentation
                uses: softprops/action-gh-release@v1
                with:
                    tag_name: ${{ env.NEW_VERSION }}
                    body: ${{ steps.get-changelog.outputs.changelog }}
                    prerelease: ${{ startsWith(github.event.inputs.releaseType, 'pre') }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
