name: "Workflows"
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup Node
                uses: actions/setup-node@v2
                with:
                    node-version: '14.x'
                    registry-url: 'https://registry.npmjs.org'
                    # Configure Git
            -   name: Git configuration
                run: |
                    npm version minor --workspace=packages --if-present
